### PR TITLE
change link from plone.org to plone.com

### PR DESCRIPTION
**Pull request by tkimnguyen**

### CODE REVIEW

**Comment by jensens** [comment]
Do think about ``target="_blank"`` - i dont think its a good idea. Its the users choice if she wants a new tab or not, not yours. I.e. I hate it if new tabs are just appearing w/o my choice.

**Comment by jensens** [comment]
ah, plone.app.layout always had it _blank. OMG, why do we have this twice (3 times with portlet)...

**Comment by tkimnguyen** [comment]
Thx @jensens - yeah I was wondering why I had to change it in three places :)

**Comment by davilima6** [comment]
Also +1 for avoiding _blank for the same a11n reasons: user must have control.

If really needed it should at least follow `External links open in new window` in @@theming-controlpanel, which btw is off by default.

**Comment by tkimnguyen** [comment]
@davilima6 I agree with you, yet in many cases when the setting is off we still really do not want users to leave the current site.

**Comment by davilima6** [comment]
I understand but the thing is we should not impose what we want but leave it as an option to the user.

The only exception is if it's an edit page or [some task that would lose information when leaving](https://css-tricks.com/use-target_blank/) (reading the page doesn't count). For everything else, I think users (and us) should rely on browser's back button.

**Comment by tkimnguyen** [comment]
That's fine with me, but the other recent changes I've made to point to plone.com instead of plone.org, plus on the default front-page, have used target="_blank". Do we need to go back and change those as well?

**Comment by davilima6** [comment]
Yes, I think that's best.

**Pull request merged**
