### PR TITLE
Fix #173

### LINKED ISSUE #173: Can't use Live Preview of theme
May be related to blog post: https://community.plone.org/t/plone-5-2-1-theming-attributeerror-requestcontainer-object-has-no-attribute-parents/11993

- Plone 5.2.0 (5207)
- CMF 2.4.0
- Zope 4.1.1
- Python 3.6.9 (default, Nov 7 2019, 10:44:02) [GCC 8.3.0]
- PIL 6.1.0 (Pillow)
- WSGI: An
- Server: waitress 1.3.

I tried to use the Live Preview (clicking on the picture of a theme) in the @@theming-controlpanel and the following Error occurred:

```AttributeError
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module plone.app.theming.browser.mapper, line 269, in getFrame
  Module plone.app.theming.utils, line 192, in findContext
AttributeError: 'RequestContainer' object has no attribute 'PARENTS'```

### PR DESCRIPTION
**Pull request by petri**
Make theme previews great again...

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
Thanks @petri for your PR!

The code before was totally borked :) 
The `findContext` function was expecting a request as an argument not an object.
It worked because it was always raising a `KeyError` or a `NotFound`, but now it raises and `AttributeError` and that triggers the error.

Checking the code it looks to me that path can assume the following values:
- `/`
- `/++theme++name/something`

The newly introduced `findPathContext` method will always return the portal object.

I would just replace the try/except with `context = portal` or use portal instead of context without introducing a new helper.

What do you think @petri? Am I missing something?

Returning the response as bytes looks to me totally right.

BTW If we could add a test for that it would be great.

**Comment by petri** [comment]
@ale-rt illustrating `path` and the corresponding `context` returned by the newly introduced `findPathContext` utility, when I click around some test content in preview, thus:
 
```python
    context = findPathContext(path) or portal
    print("context for clicked preview path '%s' is %s" % (path, context))
```

you'll see the following:

> context for clicked preview path '/testfolder' is `<Folder at testfolder>`
> context for clicked preview path '/testfolder/testdocument' is `<Document at testdocument>`

**Comment by ale-rt** [comment]
Then I definitely missed a lot!
Thanks for your work, @petri!

**Pull request merged**
