### PR TITLE
Included barceloneta theming elements

### PR DESCRIPTION
**Pull request by obct537**
Included theming elements from the barceloneta theme into the thememapper to make it look much less....not wonderful.

### CODE REVIEW

**Comment by djay** [comment]
i actually want to go the other way and remove the other way and remove the theme elements from all site setup and back end screens such as edit, contents and sharing etc.

**Comment by davilima6** [comment]
Any reason for relying on Github-based resources?

**Comment by Gagaro** [comment]
There is a real issue with using resources on master! It is absolutely NOT reliable for production.

**Comment by Gagaro** [comment]
Same issue there : https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/barceloneta.plone.local.less

**Comment by vangheem** [comment]
Yes, it would be nice to be able to include styles from a theme package but there is currently no mechanism to do it. Selecting a tag to pull from instead is mildly more safe...

**Comment by Gagaro** [comment]
What about #92 ?

**Pull request merged**
