### PR TITLE
fix: remove github dependancies in thememapper

### PR DESCRIPTION
**Pull request by Gagaro**
This used to include dependancies from master branches directly from github. This should never be done as it is very unreliable to use dev resources in production.

This also fix a bug with a mixin being added but the mixin file being not included.

### CODE REVIEW

**Comment by Gagaro** [comment]
Looks like I wasn't actually on master when I made this PR, let me recheck-it.

**Comment by Gagaro** [comment]
Looks like the mixin fix was already included in 6e6603861249eefc8c73ab36d7ec9770bc964f38 but not explicitly mentioned in the changelog/commit message.

**Comment by vangheem** [comment]
Does this work when using ./bin/plone-compile-resources?

++theme++barceloneta is a relative server location, not something on the file system.

**Comment by Gagaro** [comment]
Obviously I forgot about the obvious part. I have a few idea though, I'll test them out.

**Comment by Gagaro** [comment]
Tests should start there http://jenkins.plone.org/job/pull-request-5.0/789

**Comment by vangheem** [comment]
I wonder if we could iterate through all installed themes and add similar syntax...

**Comment by vangheem** [comment]
Thanks!

**Pull request merged**
