### PR TITLE
Fix 187

### PR DESCRIPTION
**Pull request by jensens**
see #187 

also removed unused code referring to an nowhere used test layer

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
https://github.com/search?q=org%3Aplone+THEMINGWITHCACHING&type=Code

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
hah! copy paste leftover, sorry, I'll remove (it was late already)

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Thanks. Jenkins was passing before, except an unrelated failure in one of them. I will merge.

**Comment by mauritsvanrees** [comment]
Hah, you commented five seconds before me. :-)

**Pull request merged**
