### PR TITLE
Fix imports from Globals that was removed in Zope4

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by jensens** [comment]
There is a test failure in our unstable robot tests of plone.app.theming and plone.app.querystring. 
I have no idea how this is related to the change (and if it is at all).

**Comment by jensens** [comment]
social settings again are unstable, merge anyway

**Comment by MatthewWilkes** [comment]
@jensens @esteele I'm not sure it was right to merge this into master, as it's now been released as part of Plone5, but some of these changes are Zope4 dependent.

**Comment by jensens** [comment]
Afaik in 5 all is fine not using Globals.

**Pull request merged**
