### PR TITLE
Fix transform

### PR DESCRIPTION
**Pull request by sunew**
fix AttributeError: 'NoneType' object has no attribute 'getroottree' when the result is not html / is empty.

### CODE REVIEW

**Comment by sunew** [comment]
@jensens had to delete and re-add the branch and pull request, but here goes, rebased on master:)

**Comment by jensens** [comment]
http://jenkins.plone.org/view/All/job/pull-request/104/

**Comment by sunew** [comment]
i see a test failure regarding an overlay. This could potentially have somerhing to do with my fix. Lets wait with the merge until i can investigate.

**Comment by esteele** [comment]
Where do we stand on this one?

**Comment by jensens** [comment]
- its a simple change and should be merged, 
- needs a rebase (its a fork in @sunew his github, so we cant so easily) 
- here is a test of current code: http://jenkins.plone.org/job/pull-request-5.0/66/

**Comment by sunew** [comment]
I rebased and pushed to my branch

**Comment by jensens** [comment]
again after rebase http://jenkins.plone.org/job/pull-request-5.0/70/

**Pull request merged**
