### PR TITLE
Update copy of userguide.rst in docs for docs.plone.org.

### PR DESCRIPTION
**Pull request by tmassman**
The docs for docs.plone.org were out of sync with the user guide.

### CODE REVIEW

**Comment by jensens** [comment]
@polyester @svx may one of you please review here?

**Comment by polyester** [comment]
I've done some review and cleanup. Only towards the end there is a lot of talk on portal_css; ideally that should be converted to Plone 5 resource registry language. I know that's not what @tmassman wrote, and was already in the file. As it is, it's much better than before. But some extra notes saying "in Plone 5, you should use resource registries instead of portal_css" would be great. 

There are (beginning) docs for resource-registries in 
https://github.com/plone/documentation/blob/3137525caa0b433e90f6dd516c32ab08b8e57e29/adapt-and-extend/config/resource-registries.rst
and https://github.com/plone/documentation/blob/5.0/manage/upgrading/version_specific_migration/p4x_to_p5x_upgrade.rst
to link to.

**Comment by polyester** [comment]
to be clear: if nobody manages to do those extra pointers, it can be merged, it's better than it was. But steering people away from portal_css and towards Resource Registries is the way forward.

**Comment by jensens** [comment]
So, may we merge this and add an issue for the open tasks?

**Comment by polyester** [comment]
Fine with me; I don't know the etiquette of plone.app.theming but I'd say go for it.

**Comment by jensens** [comment]
i added the missing parts at #84

**Pull request merged**
