### PR TITLE
Integrate thememapper pattern

### PR DESCRIPTION
**Pull request by ebrehault**
Note: the thememapper bundles producesa conflicts with the regular plone mockup bundle when the resource registry is in Development mode, but I do not consider that as a blocker for Plone 5 beta (and I will fix that ASAP).

### CODE REVIEW

**Comment by vangheem** [comment]
@ebrehault I'm going to try working on this today. Sorry it's taken so long.

**Comment by vangheem** [comment]
Alright, I might just pull out some of this stuff. Any reason why you included all of mockup here? Is the theme mapper stuff here consistent with mockup or do I need to merge back?

**Comment by ebrehault** [comment]
Regarding including mockup in this package, that's something I have discussed with several persons, and I am not totally sure about the right way to go: if a package needs a specific bundle, do we want to build it in the mockup package (problem: it might grow infinitely + that's not applicable for add-ons) or shall we create a local mockup (using the mockup generator)?
In this particular case, it might make sense to put it in the mockup package as plone.app.theming is part of the core. I have no strong opinion here.

Regarding consistency with current mockup master: I guess there rae few changes since @jcbrand merged patternlib, but that's probably not big. I will have a look.

**Comment by vangheem** [comment]
We definitely don't want to include it like this--really hard to keep things up to date. You probably just want to include it as a bower dependency for dev and then build a version out that plone.app.theming would ship with. If you can make sure mockup is up to date with whatever changes there might be, I can finish the integration.

**Comment by ebrehault** [comment]
@vangheem yes you are right, and initially, with the mockup generator, mockup is provided as a bower dep, but I haven't been able to work it out (mainly problems with pathes in less files).
So in order to produce the bundle, I have jut copied the mockup sources, but it is definitely not a good approach.
So, if you are ok with it, I would really prefer to define and build the bundle directly into the mockup package.

**Comment by vangheem** [comment]
Yes, that's fine. It should be done similarly to the resource registry pattern--the integration and everything

**Comment by vangheem** [comment]
Would you like me to do that or are you going to?

**Comment by ebrehault** [comment]
I will try to do it tomorrow, I'll ask your help if I get lost.

**Comment by ebrehault** [comment]
@vangheem ok I have cleaned up the package and I have created the bundle into Mockup directly (see this PR https://github.com/plone/mockup/pull/463). I have updated the bundle with the last Mockup changes and works fine.

**Comment by vangheem** [comment]
Great Eric! I'll look into it and merge it today.

**Comment by ebrehault** [comment]
@vangheem by the way I have overwriten your last commit on controlpanel.pt, I think it was covered by my changes. Hope that's ok.

**Comment by vangheem** [comment]
Yes, looks fine :)

**Comment by vangheem** [comment]
Is this functional right now? It seems like I may be missing some things. "++theme++sdfsdfds/@@plone.resourceeditor.filemanager-actions?action=dataTree 404 (Not Found)"

**Comment by ebrehault** [comment]
Yes it is functional, the needed backend is implemented in https://github.com/plone/plone.resourceeditor/pull/5 which is merged, so maybe your local plone.resourceeditor master is not up to date.

**Comment by vangheem** [comment]
ahh, I see. thanks.

**Comment by vangheem** [comment]
Awesome. I managed to finally get this merged. Will still need further tweaks, theming, etc but at least we have the basis for plone 5 theme editor.

**Comment by ebrehault** [comment]
Yes I agree, the basis is here. One thing I would really like is to enable LESS files compilation so the user could change its .less stylesheets in the inline editor and get the resulting CSS file updated automatically.

**Comment by vangheem** [comment]
Yes, and the new resource registry already does that so the relationship between the theme editor and the resource registry is a bit fuzzy--what to use where.

**Comment by ebrehault** [comment]
The resource registry does that but on client side, it does not actually create a CSS file on the server, right?

**Comment by vangheem** [comment]
There is a "Build" button that will save it to the ZODB.

**Pull request merged**
