### PR TITLE
housekeeping: pep8ified, cleanup, ...

### PR DESCRIPTION
**Pull request by jensens**
utf8 headers, sorted imports, ...

Again a code cleanup to not scare away devs looking into it. well, theres work left. 

I also unified redundant code in the different getTheme functions.

### CODE REVIEW

**Comment by jensens** [comment]
test runs here http://jenkins.plone.org/job/pull-request/102/

**Comment by jensens** [comment]
build green now, anybody for review & merge?

**Comment by vangheem** [comment]
doing a quick review

**Comment by vangheem** [comment]
The namespace stuff is weird. I can't imagine that is necessary--nothing to do with this pull request though.

**Comment by jensens** [comment]
namespaces -> see #46

**Pull request merged**
