### PR TITLE
Allows users to correctly override built-in themes.

### LINKED ISSUE #51: When copying a new theme from control panel and giving the same id, the original disappears.
I just downloaded Plone 5.0b1, and tried to copy a new theme from barceloneta. I decided to give the same id:

selecao_062

When giving the same id, now the original disappears from control panel. I need to delete the custom one to show the original again.

selecao_063

I don't know if this is the intended behavior or a bug, so I'm opening this issue.

### PR DESCRIPTION
**Pull request by obct537**
This fixes #51. It also prevents users from being able to override TTW themes.

### CODE REVIEW

**Comment by vangheem** [comment]
Do we need to set an override property? Shouldn't it just override an existing one in it is named the same when you customize or create a new one with the same id as the file system theme?

**Comment by obct537** [comment]
Not going to claim this is the best/only way to do it, but I couldn't think of another way to be able to show on the theme list that the theme is an override. Without it, it will correctly overwrite the existing one, but I couldn't find any way to denote if the theme was original or not when rendering the page. After the new theme is added, the original "disappears", so there's no way to tell that the new one is an override. Not sure if that explanation makes sense.

**Comment by vangheem** [comment]
Yes, I understand you.

I think you'll just need, while rendering the list of themes, to check if another theme of the same id/name is in the list and not editable. File system themes are not editable. 

In controlpanel.py check out the themeList method and check out the getAvailableThemes function in plone.app.theming.utils.py

**Comment by obct537** [comment]
Yeah, I looked at that. After you create the theme, the next time you render the page, getAvailableThemes only returns the new one. If you look at the methods "resources" variable in a debugger, it only shows the new one. Wherever it's hiding, it's somewhere farther up the chain.

**Comment by vangheem** [comment]
Alright. There should be a way to get all the available themes on file system and TWW. I think what angle you'll want to take is figuring out how to get the complete list instead of adding an attribute to the manifest.

You'll probably be forced into digging into some of the plone.resource...

**Comment by datakurre** [comment]
@obct537 Nathan is right. "Hiding" the filesystem theme when TTW one created is actually feature of plone.resource. Probably you should reimplement ``plone.resource.manifest.getAllResources`` into ``plone.app.theming.utils`` so that it calls ``plone.resource.utils.iterDirectoriesOfType`` with additional parameter ``filter_duplicates=False`` (that defaults to True, which causes the filtering).

**Comment by idgserpro** [comment]
I think this implementation is good enough for this problem. 

If you still think this can be improved my suggestion is to avoid messing up with plone.resource and all the reimplementation (that will lead to more tests and more maintainance) and just improve the message:

```(this overrides a filesystem theme. Delete it to show the overriden from filesystem)```

I know it's a long message, but gets the work done in the simplest way possible.

**Comment by vangheem** [comment]
Closing this PR since it's being done in another PR.

**Pull request closed without merging**
