### PR TITLE
Update to use new theme parameters in onEnabled

### PR DESCRIPTION
**Pull request by fbrun**
This update is from issue #27 : "Error on parameters passed to onEnabled in applyTheme function"

### CODE REVIEW

**Comment by datakurre** [comment]
@fbrun It seems that you are passing the theme object for onEnabled even IThemePlugin-interface says that you should pass theme name. (And that's what's passed for onDisable.)

**Comment by fbrun** [comment]
@datakurre I use the product plone.app.themingplugins with new self plugin to change ck-editor path in portal_css when changing theme in theming panel (plone control panel). In this plugin, i use "onEnabled and "onDisabled" function (header defined in plone.app.theming.interfaces.py). The values passed in this functions are automatical processed when flag "enabled" or "disabled" is detect.
At this moment, i noticed the line "plugin.onEnabled(...)" call in "def applyTheme" (plone/app/theming/utils.py) was not correctly used in some case (the theme parameter pass to this onEnabled was not the new currently applied), from which i made this correction.

For help, here is my code added for new plugin into the plone.app.themingplugins product:
<pre>
import logging

from zope.interface import implements
from zope.interface import alsoProvides
from zope.interface import Interface
from zope.interface.interface import InterfaceClass

from plone.app.theming.interfaces import IThemePlugin

from Products.CMFCore.utils import getToolByName
from zope.component.hooks import getSite

logger = logging.getLogger(__name__)

class CSSCKEditorRegistryPlugin(object):
    """This plugin dynamically add or remove ck-editor.css in portal_css
    when the theme is enabled or disabled.

    You have to add in the manifest the cssckeditorregistry section with the css id::

        [theme:cssckeditorregistry]
        id = ++theme++themefoldername/css/ck-editor.css

        the themefoldername is the name of the theme folder, unique for the instance
    """

    implements(IThemePlugin)

    dependencies = ('browserlayer',)

    def onDiscovery(self, theme, settings, dependenciesSettings):
        pass

    def onCreated(self, theme, settings, dependenciesSettings):
        pass

    def onEnabled(self, theme, settings, dependenciesSettings):
        if 'cssckeditorregistry' in dependenciesSettings and 'id' in settings:
            site = getSite()
            portal_css = getToolByName(site, 'portal_css')
            portal_css_ids = portal_css.getResourceIds()
            
            id_css = settings['id']
            if id_css in portal_css_ids:
                portal_css.manage_removeStylesheet(id=id_css)
            
            portal_css.manage_addStylesheet(id = id_css,
                                        rel = 'stylesheet',
                                        expression = "request/HTTP_X_THEME_ENABLED | nothing",
                                        media = 'all',
                                        compression='safe',
                                        rendering='link',
                                        cookable=True,
                                        cacheable=True,
                                        enabled = True,
                                        applyPrefix = True)

    def onDisabled(self, theme, settings, dependenciesSettings):
        if 'cssckeditorregistry' in dependenciesSettings and 'id' in settings:
            site = getSite()
            portal_css = getToolByName(site, 'portal_css')
            portal_css_ids = portal_css.getResourceIds()
            
            id_css = settings['id']
            if id_css in portal_css_ids:
                portal_css.manage_removeStylesheet(id=id_css)

    def onRequest(self, request, theme, settings, dependenciesSettings):
        pass
</pre>

**Comment by datakurre** [comment]
@fbrun If you have time, could you confirm that some of my pulls referred earlier (each for a specific p.a.theming branch) works for you? The we could merge them instead. Your code does not seem to use the theme variable, so changing it from theme object to theme string (as specified in IThemePlugin) would not break your plugins.

**Comment by fbrun** [comment]
@datakurre ok i'll test your pulls and i'll tell you if it's work for me. Thanks

**Comment by fbrun** [comment]
@datakurre ok, i've tested your pull #40 on plone.app.theming v1.2.1 and it's works for me.
I've tested to activate a theme, then change this by another and deactivate it, all is good.
Thanks

**Comment by datakurre** [comment]
@fbrun Thanks a lot for testing. So, I'll close this pull and refresh #40 for the others to merge.

**Pull request closed without merging**
